server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
    nonSecurePort: 80

spring:
  application:
    name: usuario-ecommerce-service
  data:
    mongodb:
      database: usuarios
      port: 27017
      host: usuarios-mongo
